name = "atcf_riscv_grip"
default_config  = "notools"
configs         = ["withtools", "notools"]
base_repos      = ["atcf_riscv_tests", "grip"]
stages          = ["download", "configure", "compile", "install"]
workflow        = "readonly"

[env]
TOOLS_DIR="%GRIP_ROOT_PATH%/tools"
RISCV_TOOLS_PREFIX="%TOOLS_DIR%/bin/riscv32-elf-"
PATH="%GRIP_ROOT_PATH%/grip:$(PATH)"

[config.notools]

[config.withtools]
repos = ["toolchains"]

[repo.grip]
url  = "https://github.com/atthecodeface/grip.git"
path = "grip"

[repo.atcf_riscv_tests]
url  = "https://github.com/atthecodeface/riscv-atcf-tests.git"
path = "atcf_riscv_tests"

[repo.atcf_riscv_tests.configure]
env = {}
exec = "make RISCV_TOOLS_PREFIX=%RISCV_TOOLS_PREFIX% clean"

[repo.atcf_riscv_tests.compile]
env = {}
requires = ["atcf_riscv_tests.configure"]
exec = "make RISCV_TOOLS_PREFIX=%RISCV_TOOLS_PREFIX%"

[repo.toolchains]
url = "toolchain_building.git"
path = "toolchains"
env = { TOOLS_DATA_DIR="%GRIP_ROOT_PATH%/temp_data" }

[repo.toolchains.download]
exec = "make DATA_DIR=%TOOLS_DATA_DIR% INSTALL_DIR=%TOOLS_DIR% download"

[repo.toolchains.configure]
requires = ["toolchains.download"]
exec = "make TARGET=riscv32-elf DATA_DIR=%TOOLS_DATA_DIR% INSTALL_DIR=%TOOLS_DIR% configure"

[repo.toolchains.install]
requires = ["toolchains.configure"]
exec = "make TARGET=riscv32-elf DATA_DIR=%TOOLS_DATA_DIR% INSTALL_DIR=%TOOLS_DIR% install"

