name = "atcf_riscv_grip"
default_config  = "notools"
configs         = ["all", "notools"]
base_repos      = ["atcf_riscv_tests", "grip"]
stages          = ["compile", "configure","install"]
workflow        = "readonly"

[env]
HOST_TOOLS_DIR="%GRIP_ROOT_PATH%/tools/host"
RISCV_TOOLS_DIR="%GRIP_ROOT_PATH%/tools/riscv"
PATH="%GRIP_ROOT_PATH%/grip:$(PATH)"

[config.notools]

[config.all]
repos = ["grip", "cdl", "binutils"]

[repo.grip]
url  = "https://github.com/atthecodeface/grip.git"
path = "grip"

[repo.atcf_riscv_tests]
url  = "https://github.com/atthecodeface/riscv-atcf-tests.git"
path = "atcf_riscv_tests"
[repo.cdl.compile]
exec = ""

[repo.binutils]
url = "%SOURCEWARE_ORG%/binutils-gdb.git"
branch = "binutils-2_32-branch"
path = "binutils"
shallow = "true"
env = { BINUTILS_BUILD_DIR="%GRIP_ROOT_PATH%/build/binutils" }

[repo.binutils.configure]
env = {BUILD_DIR="%BINUTILS_BUILD_DIR%"}
exec = """ \
mkdir -p %BUILD_DIR% &&  \
cd %BUILD_DIR% &&        \
%GRIP_REPO_PATH%/configure --prefix=%RISCV_TOOLS_DIR% --target=riscv64-unknown-elf \
"""

[repo.binutils.install]
requires = ["binutils.configure"]
wd = "%BINUTILS_BUILD_DIR%"
exec = """ \
 make -j8 &&   \
 make install  \
  """

